INSERT INTO public.products (slug, title, tagline, description, category, tech, tags, price_cents, status, quality_score, license_type, repo_visibility)
VALUES
('telehealth-clinic-suite','Telehealth Clinic Suite','HIPAA-minded telehealth platform with video visits and EHR-lite records','A production healthcare platform: patient onboarding, clinician scheduling, secure video consultation rooms, prescription notes, and an EHR-lite medical record timeline. Includes role separation for patients, clinicians and hospital admins, audit logging and encrypted document storage.','web-app',ARRAY['React','TypeScript','Postgres','WebRTC','Tailwind'],ARRAY['healthcare','telehealth','hospital','clinic','patient','ehr','medical'],7900,'published',94,'single_developer','private'),
('ai-diagnostics-dashboard','AI Diagnostics Dashboard','Hospital operations and AI-assisted diagnostic triage dashboard','Hospital command dashboard with bed occupancy, department load, lab turnaround metrics and an AI diagnostic triage assistant that ranks patient cases by urgency. Ships with charting, cohort filters, exportable reports and a clinician review queue.','dashboard',ARRAY['React','TypeScript','Recharts','Postgres'],ARRAY['healthcare','hospital','diagnostic','medical','patient','ai'],8900,'published',92,'single_developer','private'),
('school-lms-platform','School LMS Platform','Full learning management system for schools and academies','Complete LMS: course builder, lesson video hosting hooks, student enrollment, assignment submission, grading workbench, attendance and parent portals. Multi-role access for students, teachers and school administrators with term-based reporting.','web-app',ARRAY['React','TypeScript','Postgres','Tailwind'],ARRAY['edtech','education','school','lms','course','student','learning'],6900,'published',93,'single_developer','private'),
('exam-engine-pro','Exam Engine Pro','Online exam and proctoring engine with instant grading','Timed online exam engine with question banks, randomized papers, auto-grading, anti-cheat focus tracking, tutor review of written answers and cohort analytics. Designed for schools, tutoring companies and certification providers.','web-app',ARRAY['React','TypeScript','Postgres','Zod'],ARRAY['edtech','education','exam','student','school','tutor','learning'],5900,'published',91,'single_developer','private')
ON CONFLICT (slug) DO NOTHING;

DROP POLICY IF EXISTS "Buyers read own payment proofs" ON storage.objects;
CREATE POLICY "Admins read payment proofs" ON storage.objects
FOR SELECT TO authenticated
USING (bucket_id = 'payment-proofs' AND public.has_role(auth.uid(), 'admin'));